Repository GlueOps/glueops-dev, pull requests merged in 2024-10, with the labels that each got.

#112 Update and rename ghcr.yaml to container_image.yaml
  .github/workflows/container_image.yaml
  .github/workflows/ghcr.yaml
Labels: enhancement, configuration changes, Review effort [1-5]: 2

#123 [skip actions] synced file(s) with internal-GlueOps/github-shared-files-sync
  .github/release.yml
Labels: Review effort [1-5]: 1, configuration changes, sync

#120 chore(deps): update node.js to v20.18.0
  package.json
  yarn.lock
Labels: patch, include-in-release-notes, auto-update, dependencies

#122 chore(deps): update node.js to 967bab2
  Dockerfile
Labels: patch, include-in-release-notes, Review effort [1-5]: 1, auto-update, dependencies

#119 chore(deps): update dependency typescript to v5.6.3
  package-lock.json
  package.json
  yarn.lock
Labels: patch, include-in-release-notes, Review effort [1-5]: 1, auto-update, dependencies

#117 chore(deps): update dependency @docusaurus/module-type-aliases to v3.5.2
  package-lock.json
  package.json
  yarn.lock
Labels: patch, include-in-release-notes, Review effort [1-5]: 1, auto-update
